// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsIfqA8ykkQcAeNuF6_ZqA1LTO3DKKfhQ',
    appId: '1:365614083643:web:9cadb3184c33b3c508b61e',
    messagingSenderId: '365614083643',
    projectId: 'cloneapp-3bfa4',
    authDomain: 'cloneapp-3bfa4.firebaseapp.com',
    storageBucket: 'cloneapp-3bfa4.appspot.com',
    measurementId: 'G-X2C1N6SHR7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1dR3tr_P-qKWpmi1pjcBDmESP1nHj23A',
    appId: '1:365614083643:android:28ff7ced1f46810108b61e',
    messagingSenderId: '365614083643',
    projectId: 'cloneapp-3bfa4',
    storageBucket: 'cloneapp-3bfa4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASLVMdt2TPM8qKkT4lZBk_MqPRb7zEYhE',
    appId: '1:365614083643:ios:06652143fc3f625c08b61e',
    messagingSenderId: '365614083643',
    projectId: 'cloneapp-3bfa4',
    storageBucket: 'cloneapp-3bfa4.appspot.com',
    androidClientId: '365614083643-ik8j27c71k68irra1amsspluu103ak74.apps.googleusercontent.com',
    iosClientId: '365614083643-439noddeb9g0o9k9krne29gvj8qid244.apps.googleusercontent.com',
    iosBundleId: 'com.example.cloneShoppe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASLVMdt2TPM8qKkT4lZBk_MqPRb7zEYhE',
    appId: '1:365614083643:ios:dfa3debfd60f74d308b61e',
    messagingSenderId: '365614083643',
    projectId: 'cloneapp-3bfa4',
    storageBucket: 'cloneapp-3bfa4.appspot.com',
    androidClientId: '365614083643-ik8j27c71k68irra1amsspluu103ak74.apps.googleusercontent.com',
    iosClientId: '365614083643-udlmd225mp957gcjftg5ulkt7bq8n57p.apps.googleusercontent.com',
    iosBundleId: 'com.example.cloneShoppe.RunnerTests',
  );
}
